# Generated by Django 5.1.1 on 2024-09-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0015_alter_car_mileage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="maintenance",
            name="car",
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[("Confirmed", "Confirmed"), ("Completed", "Completed")],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="fuel_type",
            field=models.CharField(
                choices=[
                    ("Petrol", "Petrol"),
                    ("Diesel", "Diesel"),
                    ("Electric", "Electric"),
                    ("Hybrid", "Hybrid"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="transmission",
            field=models.CharField(
                choices=[("Automatic", "Automatic"), ("Manual", "Manual")],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="type",
            field=models.CharField(
                choices=[
                    ("Suv", "SUV"),
                    ("Sedan", "Sedan"),
                    ("Hatchback", "Hatchback"),
                    ("Convertible", "Convertible"),
                    ("Coupe", "Coupe"),
                    ("Wagon", "Wagon"),
                    ("Pickup", "Pickup Truck"),
                    ("Minivan", "Minivan"),
                    ("Sports Car", "Sports Car"),
                    ("Luxury", "Luxury"),
                    ("Crossover", "Crossover"),
                    ("Roadster", "Roadster"),
                    ("Coupe SUV", "Coupe SUV"),
                ],
                max_length=50,
            ),
        ),
        migrations.DeleteModel(
            name="Insurance",
        ),
        migrations.DeleteModel(
            name="Maintenance",
        ),
    ]
