# Generated by Django 5.1.1 on 2024-09-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0016_remove_maintenance_car_alter_booking_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_status",
            field=models.CharField(choices=[("Success", "Success")], max_length=50),
        ),
    ]
