# Generated by Django 5.1.1 on 2024-09-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0017_alter_payment_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="dummy",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
