# Generated by Django 5.1.1 on 2024-09-20 20:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0018_customer_dummy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="dummy",
        ),
    ]
